{{- if and .Values.back.enabled .Values.back.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-back
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Cache-control: public, max-age=3600";
      if ($request_uri !~ \.) {
          more_set_headers "Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0'";
      }
      more_set_headers "server: hide";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Xss-Protection: 1";
      sub_filter_once off;
      sub_filter random-csp-nonce $request_id;
      more_set_headers "Strict-Transport-Security max-age=31536000; includeSubDomains";
      more_set_headers "Content-Security-Policy: default-src 'self'; font-src 'unsafe-inline' 'self' data:; style-src 'unsafe-inline' 'self'; script-src 'unsafe-inline' 'self' https://plausible.algonomia.com; connect-src 'self' https://plausible.algonomia.com; object-src 'none'; frame-src 'self'; img-src 'self' https://media.licdn.com data:; Form-Action 'self'";
    {{- if .Values.global.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.tls.clusterIssuer }}
    {{- end }}
spec:
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.ingress.host }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          - path: {{ .Values.global.ingress.baseUrl | trimSuffix "/" }}{{ .Values.back.ingress.path }}?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.back.service.name }}
                port:
                  number: {{ .Values.back.service.port }}
{{- end }}
